creation_rules:

  - name: beta
    path_regex: \.env\.beta\.secrets.*$
    age: >-
      age1vq7sw98g2xk9md2yg9f959k8xkaz8r32pds27jn3nsfcdue3757s0h7hd8

  - name: prod
    path_regex: \.env\.prod\.secrets.*$
    age: >-
      age1h8wnpa5lx2vgn2h64lgpeanuct8q2tvzxvn5xmvms7exmwvmu9zq5str5w
