networks:
    keating-dev:
        driver: bridge
    traefik-proxy-blumilk-local:
        external: true

volumes:
    keating-postgres-data:
        name: keating-postgres-data
    keating-redis-data:
        name: keating-redis-data

services:
    app:
        build:
            context: ./environment/dev/app
            dockerfile: Dockerfile
            args:
                - INSTALL_XDEBUG=${DOCKER_INSTALL_XDEBUG:-true}
                - USER_ID=${DOCKER_HOST_USER_ID:-1000}
        labels:
            - "traefik.enable=true"
            - "traefik.blumilk.environment=true"
            # HTTP
            - "traefik.http.routers.keating-http-router.rule=Host(`keating.blumilk.localhost`)"
            - "traefik.http.routers.keating-http-router.entrypoints=web"
            # HTTP to HTTPS redirect
            #      - "traefik.http.routers.keating-http-router.middlewares=https-redirect@file"
            # HTTPS
            - "traefik.http.routers.keating-https-router.rule=Host(`keating.blumilk.localhost`)"
            - "traefik.http.routers.keating-https-router.entrypoints=websecure"
            - "traefik.http.routers.keating-https-router.tls=true"
        container_name: keating-app-dev
        working_dir: /application
        volumes:
            - ./environment/dev/app/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./environment/dev/app/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
            - ./environment/dev/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
            - ./environment/dev/app/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
            - .:/application
        ports:
            - ${DOCKER_APP_HOST_PORT:-3851}:80
        networks:
            - keating-dev
            - traefik-proxy-blumilk-local
        restart: unless-stopped
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:15.5-alpine3.17@sha256:1961f9d61a86948fb3c02ef87a6616f74f3530d10a1cd299b84abba7ed6db791
        container_name: keating-db-dev
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - PGDATA=/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname ${DB_DATABASE} --username ${DB_USERNAME}"]
            interval: 3s
            timeout: 3s
            retries: 5
        ports:
            - ${DOCKER_DATABASE_HOST_PORT:-3853}:5432
        volumes:
            - ./environment/dev/postgres/init-unaccent.sql:/docker-entrypoint-initdb.d/init-unaccent.sql
            - keating-postgres-data:/var/lib/postgresql/data
        networks:
            - keating-dev
        restart: unless-stopped

    mailpit:
      image: axllent/mailpit:v1.19.3@sha256:8fbe10f22c09c769ad678bd14e2f9858e41d5e199ea043efe207f85f279fd594
      container_name: keating-mailpit-dev
      labels:
        - "traefik.enable=true"
        - "traefik.blumilk.environment=true"
        - "traefik.http.routers.keating-mailpit-http-router.rule=Host(`keating-mailpit.blumilk.localhost`)"
        - "traefik.http.routers.keating-mailpit-http-router.entrypoints=web"
        - "traefik.http.routers.keating-mailpit-https-router.rule=Host(`keating-mailpit.blumilk.localhost`)"
        - "traefik.http.routers.keating-mailpit-https-router.entrypoints=websecure"
        - "traefik.http.routers.keating-mailpit-https-router.tls=true"
        - "traefik.http.services.keating-mailpit.loadbalancer.server.port=8025"
      networks:
        - keating-dev
        - traefik-proxy-blumilk-local
      ports:
        - ${DOCKER_MAILPIT_DASHBOARD_HOST_PORT:-3854}:8025
      restart: unless-stopped

    redis:
        image: redis:7.0.11-alpine3.17@sha256:cbcf5bfbc3eaa232b1fa99e539459f46915a41334d46b54bf894f8837a7f071e
        container_name: keating-redis-dev
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-3852}:6379
        volumes:
            - keating-redis-data:/data
        networks:
            - keating-dev
        restart: unless-stopped
