networks:
  traefik-proxy:
    external: true
  keating-prod:
    driver: bridge
    name: keating-prod

volumes:
  keating-prod-postgres-data:
    name: keating-prod-postgres-data
  keating-prod-redis-data:
    name: keating-prod-redis-data

services:
  database:
    image: postgres:15.5-alpine3.17@sha256:1961f9d61a86948fb3c02ef87a6616f74f3530d10a1cd299b84abba7ed6db791
    container_name: keating-prod-database
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DB_DATABASE} --username ${DB_USERNAME}" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - ../../../postgres/init-unaccent.sql:/docker-entrypoint-initdb.d/init-unaccent.sql
      - keating-prod-postgres-data:/var/lib/postgresql/data
    networks:
      - keating-prod
    restart: unless-stopped

  redis:
    image: redis:7.0.11-alpine3.17@sha256:cbcf5bfbc3eaa232b1fa99e539459f46915a41334d46b54bf894f8837a7f071e
    container_name: keating-prod-redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - keating-prod-redis-data:/data
    networks:
      - keating-prod
    restart: unless-stopped
