networks:
  traefik-proxy:
    external: true
  keating-prod:
    driver: bridge
    name: keating-prod

services:
  keating-kpiech-prod-app:
    image: registry.blumilk.pl/internal-public/keating:kpiech
    container_name: keating-kpiech-app-container
    pull_policy: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      - "traefik.http.routers.kpiech.rule=${TRAEFIK_ROUTER_RULE}"
      - "traefik.http.routers.kpiech.entrypoints=websecure"
      - "traefik.http.routers.kpiech.tls=true"
      - "traefik.http.routers.kpiech.tls.certresolver=lets-encrypt-resolver"
      - "traefik.http.routers.kpiech.middlewares=response-gzip-compress@file,no-index-robots-response-header@file"
    working_dir: /application
    volumes:
      - ./.env:/application/.env:ro
    networks:
      - keating-prod
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .deployment
