networks:
  traefik-proxy:
    external: true
  keating-beta:
    driver: bridge

volumes:
  keating-beta-pgsql-data:
    name: keating-beta-pgsql-data
  keating-beta-redis-data:
    name: keating-beta-redis-data

services:
  keating-beta-app:
    image: registry.blumilk.pl/internal-public/keating:beta
    container_name: keating-beta-app
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keating-beta-app.rule=Host(`${KEATING_HOST_NAME:? variable KEATING_HOST_NAME not set}`)"
      - "traefik.http.routers.keating-beta-app.entrypoints=websecure"
      - "traefik.http.routers.keating-beta-app.tls=true"
      - "traefik.http.routers.keating-beta-app.tls.certresolver=lets-encrypt-resolver"
      - "traefik.http.routers.keating-beta-app.middlewares=response-gzip-compress@file"
    depends_on:
      keating-beta-database:
        condition: service_healthy
      keating-beta-redis:
        condition: service_healthy
    working_dir: /application
    volumes:
      - ./.env:/application/.env:ro
    networks:
      - keating-beta
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .deployment

  keating-beta-database:
    image: postgres:15.5-alpine3.17@sha256:1961f9d61a86948fb3c02ef87a6616f74f3530d10a1cd299b84abba7ed6db791
    container_name: keating-beta-database
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      - PGPASSWORD=${DOCKER_KEATING_BETA_DB_ROOT_PASSWORD:? variable DOCKER_KEATING_BETA_DB_ROOT_PASSWORD not set}
      - POSTGRES_DB=${DOCKER_KEATING_BETA_DB_DATABASE:? variable DOCKER_KEATING_BETA_DB_DATABASE not set}
      - POSTGRES_USER=${DOCKER_KEATING_BETA_DB_USERNAME:? variable DOCKER_KEATING_BETA_DB_USERNAME not set}
      - POSTGRES_PASSWORD=${DOCKER_KEATING_BETA_DB_PASSWORD:? variable DOCKER_KEATING_BETA_DB_PASSWORD not set}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DOCKER_KEATING_BETA_DB_DATABASE} --username ${DOCKER_KEATING_BETA_DB_USERNAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - keating-beta-pgsql-data:/var/lib/postgresql/data
    networks:
      - keating-beta
    restart: unless-stopped

  keating-beta-redis:
    image: redis:7.0.11-alpine3.17@sha256:cbcf5bfbc3eaa232b1fa99e539459f46915a41334d46b54bf894f8837a7f071e
    container_name: keating-beta-redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - keating-beta-redis-data:/data
    networks:
      - keating-beta
    restart: unless-stopped
